using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using Kinect = Windows.Kinect;
using Unity.VisualScripting;

// initially generated by Deepseek; further edits made by hand
public class KinectInputSystem : MonoBehaviour
{
    public BodySourceManager bodySourceManager;
    
    [Header("Gesture Thresholds")]
    public float handRaiseThreshold = 0.3f;
    public float leanThreshold = 0.15f;
    public float swipeDistance = 0.5f;
    public float gestureHoldTime = 0.5f;
    
    // Virtual buttons state
    private Dictionary<string, bool> buttonStates = new Dictionary<string, bool>();
    private Dictionary<string, float> buttonHoldTimers = new Dictionary<string, float>();
    private Dictionary<ulong, Dictionary<string, bool>> userButtonStates = new Dictionary<ulong, Dictionary<string, bool>>();
    
    // Gesture tracking
    private Dictionary<ulong, Vector3> previousHandPositions = new Dictionary<ulong, Vector3>();
    
    public static KinectInputSystem Instance { get; private set; }
    
    // Define virtual buttons
    public readonly string[] VirtualButtons = {
        "Kinect_Jump",
        "Kinect_RightHandRaised", // stop
        "Kinect_LeftHandRaised", // go
        "Kinect_LeanLeft",
        "Kinect_LeanRight", 
        "Kinect_SwipeRight",
        "Kinect_SwipeLeft",
        "Kinect_RightHandForward",
        "Kinect_LeftHandForward",
        "Kinect_RightHandHorizontal", // turn right
        "Kinect_LeftHandHorizontal", // turn left
        "Kinect_LeftLegSideRaise", // move left
        "Kinect_RightLegSideRaise", // move right
        "Kinect_Bow" // start
    };
    
    void Awake()
    {
        if (Instance == null)
        {
            Instance = this;
            DontDestroyOnLoad(gameObject);
            InitializeButtonSystem();
        }
        else
        {
            Destroy(gameObject);
        }
    }
    
    Vector3 lastLeftFootPos = Vector3.zero;
    Vector3 lastRightFootPos = Vector3.zero;
    void InitializeButtonSystem()
    {
        foreach (string button in VirtualButtons)
        {
            buttonStates[button] = false;
            buttonHoldTimers[button] = 0f;
        }

        if (bodySourceManager == null) return;

        Windows.Kinect.Body[] bodies = bodySourceManager.GetData();
        if (bodies == null) return; 

        var leftFoot = bodies[0].Joints[Kinect.JointType.FootLeft];
        var rightFoot = bodies[0].Joints[Kinect.JointType.FootRight];
        lastLeftFootPos = new Vector3(leftFoot.Position.X, leftFoot.Position.Y, leftFoot.Position.Z);
        lastRightFootPos = new Vector3(rightFoot.Position.X, rightFoot.Position.Y, rightFoot.Position.Z);
    }
    
    void Update()
    {
        ResetButtonStates();
        ProcessKinectInput();
        UpdateButtonTimers();
    }
    
    void ResetButtonStates()
    {
        // Reset all buttons at start of frame
        foreach (string button in VirtualButtons)
        {
            buttonStates[button] = false;
        }
    }
    
    void ProcessKinectInput()
    {
        if (bodySourceManager == null) return;

        Windows.Kinect.Body[] bodies = bodySourceManager.GetData();
        if (bodies == null) return;
        
        foreach (var body in bodies)
        {
            if (body != null && body.IsTracked)
            {
                ProcessBodyGestures(body);
            }
        }
    }
    void ProcessBodyGestures(Windows.Kinect.Body body)
    {
        ulong trackingId = body.TrackingId;
        
        // Get key joints
        var spineMid = body.Joints[Kinect.JointType.SpineMid];
        var rightHand = body.Joints[Kinect.JointType.HandRight];
        var leftHand = body.Joints[Kinect.JointType.HandLeft];
        var head = body.Joints[Kinect.JointType.Head];
        var spineBase = body.Joints[Kinect.JointType.SpineBase];
        var spineShoulder = body.Joints[Kinect.JointType.SpineShoulder];
        var rightFoot = body.Joints[Kinect.JointType.FootRight];
        var leftFoot = body.Joints[Kinect.JointType.FootLeft];

        // Check for raised hands (button press)
        if (rightHand.Position.Y > head.Position.Y + handRaiseThreshold)
        {
            SetButtonPressed("Kinect_RightHandRaised");
        }
        
        if (leftHand.Position.Y > head.Position.Y + handRaiseThreshold)
        {
            SetButtonPressed("Kinect_LeftHandRaised");
        }
        
        // Check for jumping
        if (lastLeftFootPos.y + 0.1f < leftFoot.Position.Y && lastRightFootPos.y + 0.1f < rightFoot.Position.Y)
        {
            SetButtonPressed("Kinect_Jump");
        }

        // Check for bowing
        if (spineMid.Position.Y < spineBase.Position.Y + 0.2f)
        {
            SetButtonPressed("Kinect_Bow");
        }

        // Check for leaning
        if (spineMid.Position.X < spineShoulder.Position.X - leanThreshold)
        {
            SetButtonPressed("Kinect_LeanLeft");
        }
        else if (spineMid.Position.X > spineShoulder.Position.X + leanThreshold)
        {
            SetButtonPressed("Kinect_LeanRight");
        }
        
        // Check for forward hand movements
        if (rightHand.Position.Z < spineShoulder.Position.Z - 0.3f)
        {
            SetButtonPressed("Kinect_RightHandForward");
        }
        
        if (leftHand.Position.Z < spineShoulder.Position.Z - 0.3f)
        {
            SetButtonPressed("Kinect_LeftHandForward");
        }

        // Check for horizontal hand positions
        if (rightHand.Position.X > spineMid.Position.X + 0.3f) // make sure x position of hand is greater than spine mid (because on right side)
        {
            SetButtonPressed("Kinect_RightHandHorizontal");
        }
        if (leftHand.Position.X < spineMid.Position.X - 0.3f) // make sure x position of hand is less than spine mid (because on left side)
        {
            SetButtonPressed("Kinect_LeftHandHorizontal");
        }

        // Check for leg side raises
        if (rightFoot.Position.X > spineBase.Position.X + 0.2f)
        {
            SetButtonPressed("Kinect_RightLegSideRaise");
        }
        if (leftFoot.Position.X < spineBase.Position.X - 0.2f)
        {
            SetButtonPressed("Kinect_LeftLegSideRaise");
        }

        // Swipe detection
        //DetectSwipes(body, trackingId);

        // Update last foot positions
        lastLeftFootPos = new Vector3(leftFoot.Position.X, leftFoot.Position.Y, leftFoot.Position.Z);
        lastRightFootPos = new Vector3(rightFoot.Position.X, rightFoot.Position.Y, rightFoot.Position.Z);
    }

    // not planning on using swipe detection
    void DetectSwipes(Windows.Kinect.Body body, ulong trackingId)
    {
        var currentRightHandPos = GetVector3FromJoint(body.Joints[Kinect.JointType.HandRight]);
        
        if (!previousHandPositions.ContainsKey(trackingId))
        {
            previousHandPositions[trackingId] = currentRightHandPos;
            return;
        }
        
        Vector3 previousPos = previousHandPositions[trackingId];
        Vector3 delta = currentRightHandPos - previousPos;
        
        // Check for horizontal swipe
        if (Mathf.Abs(delta.x) > swipeDistance && Mathf.Abs(delta.x) > Mathf.Abs(delta.y))
        {
            if (delta.x > 0)
            {
                SetButtonPressed("Kinect_SwipeRight");
            }
            else
            {
                SetButtonPressed("Kinect_SwipeLeft");
            }
        }
        
        previousHandPositions[trackingId] = currentRightHandPos;
    }
    
    void SetButtonPressed(string buttonName)
    {
        buttonStates[buttonName] = true;
        buttonHoldTimers[buttonName] = gestureHoldTime;
    }
    
    void UpdateButtonTimers()
    {
        foreach (string button in VirtualButtons)
        {
            if (buttonHoldTimers[button] > 0)
            {
                buttonHoldTimers[button] -= Time.deltaTime;
            }
        }
    }

    // Public API for other scripts to use - mimics Input.GetButton methods
    #region Public API
    public static bool GetButton(string buttonName)
    {
        if (Instance == null) return false;
        return Instance.buttonStates.ContainsKey(buttonName) && Instance.buttonStates[buttonName];
    }
    
    public static bool GetButtonDown(string buttonName)
    {
        if (Instance == null) return false;
        
        // For GetButtonDown, we check if the button was pressed this frame
        // and the hold timer is fresh
        if (Instance.buttonStates.ContainsKey(buttonName) && 
            Instance.buttonStates[buttonName] && 
            Instance.buttonHoldTimers[buttonName] >= Instance.gestureHoldTime - Time.deltaTime)
        {
            return true;
        }
        return false;
    }
    
    public static bool GetButtonUp(string buttonName)
    {
        // This is trickier with gestures, but you can implement based on your needs
        // For now, return false or implement based on gesture release detection
        return false;
    }
    
    public static float GetButtonHoldTime(string buttonName)
    {
        if (Instance == null) return 0f;
        return Instance.buttonHoldTimers.ContainsKey(buttonName) ? Instance.buttonHoldTimers[buttonName] : 0f;
    }
    
    private Vector3 GetVector3FromJoint(Kinect.Joint joint)
    {
        return new Vector3(joint.Position.X * 10, joint.Position.Y * 10, joint.Position.Z * 10);
    }
    #endregion
}